### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by I-love-study** [I-love-study/py-rotaeno-stablizer-gui#6]
## ToDo List

- [x] 重构逻辑结构
  - [x] 使用 ffmpeg 生成视频（#1）
  - [x] 使用 skia-python 生成背景图片等
- [ ] 重构 UI
  - [ ] 使用 `tkintertools` 对 UI 进行重新绘制 `✏️Doing`
  - [ ] 将框架设计成支持多国语言支持
- [ ] 视频掩码(mask)生成（以实现 PR 等工具的二次创作）

**Comment by I-love-study** [comment]
List Upgrade:

- [ ] 确保 `config.toml` 功能可用
- [ ] 检查 `cli`, `cmd` 调用方法可以顺利调用
- [ ] 尝试使用快捷方式 + 相对路径的方式将代码放置一个文件夹内
